server {
    listen 80 ;
    server_name localhost;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    charset utf-8;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;  #VUE，配置路由（必須）
    }

    location = /robots.txt  {
        access_log off;
        log_not_found off;
    }

    access_log off;
    error_log  /var/log/nginx/blog.myapp.com-error.log error;

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
